# Generated by Django 3.1.5 on 2021-05-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set(),
        ),
    ]
