# Generated by Django 3.0.7 on 2021-06-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('AnswerId', models.AutoField(primary_key=True, serialize=False)),
                ('Answer', models.CharField(blank=True, max_length=50)),
                ('Question', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('DOB', models.DateField()),
                ('ContactNumber', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('LinkId', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(blank=True, max_length=50)),
                ('Answer', models.CharField(blank=True, max_length=50)),
                ('SubCategory', models.CharField(blank=True, max_length=50)),
                ('Link', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionId', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCat',
            fields=[
                ('SubCatId', models.AutoField(primary_key=True, serialize=False)),
                ('Answer', models.CharField(blank=True, max_length=50)),
                ('Question', models.CharField(blank=True, max_length=50)),
                ('SubCategory', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
