# Generated by Django 3.0.7 on 2021-06-02 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questionId',
            new_name='QuestionId',
        ),
    ]
